# Конфигурационный файл Alembic для системы управления версиями программного обеспечения для тракторов
# ===============================================================================================

# Основная конфигурация Alembic
[alembic]
# Путь к скриптам миграции (по умолчанию папка alembic в текущей директории)
script_location = %(here)s/alembic

# Шаблон для генерации имен файлов миграций
# По умолчанию используется %%(rev)s_%%(slug)s
# Раскомментируйте строку ниже, если хотите, чтобы файлы были с префиксом даты и времени
# file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s

# Путь sys.path, который будет добавлен в sys.path, если присутствует
# по умолчанию - текущая рабочая директория
prepend_sys_path = .

# Разделитель путей для списков файлов
# Использует os.pathsep. Конфигурация по умолчанию для новых проектов.
path_separator = os

# URL базы данных. Используется скриптом env.py для подключения к базе данных
sqlalchemy.url = postgresql+psycopg2://user:root@10.100.16.187:5433/postgres


# Хуки после записи файлов миграции
[post_write_hooks]
# post_write_hooks определяет скрипты или Python-функции, которые выполняются
# на вновь созданных скриптах миграции. См. документацию для подробностей и примеров

# форматирование с помощью "black" - использовать запуск console_scripts, через точку входа "black"
# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = -l 79 REVISION_SCRIPT_FILENAME

# линтинг с попыткой исправления с помощью "ruff" - использовать запуск модуля, через модуль "ruff"
# hooks = ruff
# ruff.type = module
# ruff.module = ruff
# ruff.options = check --fix REVISION_SCRIPT_FILENAME

# Альтернативно, используйте exec runner для выполнения бинарного файла, найденного в PATH
# hooks = ruff
# ruff.type = exec
# ruff.executable = ruff
# ruff.options = check --fix REVISION_SCRIPT_FILENAME

# Конфигурация логирования
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
