"""add dealer_notifications table

Revision ID: 5677c6e35fe7
Revises: 5a73a391494d
Create Date: 2026-04-25 12:42:24.253878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5677c6e35fe7'
down_revision: Union[str, Sequence[str], None] = '5a73a391494d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealer_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('tractor_id', sa.Integer(), nullable=True),
    sa.Column('tractor_vin', sa.String(length=17), nullable=True),
    sa.Column('software_id', sa.Integer(), nullable=False),
    sa.Column('software_name', sa.String(length=255), nullable=False),
    sa.Column('software_version', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['software_id'], ['softwares.id'], ),
    sa.ForeignKeyConstraint(['tractor_id'], ['tractors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dealer_notifications_dealer_id'), 'dealer_notifications', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_dealer_notifications_id'), 'dealer_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_dealer_notifications_is_read'), 'dealer_notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_dealer_notifications_tractor_id'), 'dealer_notifications', ['tractor_id'], unique=False)
    op.create_index(op.f('ix_dealer_notifications_tractor_vin'), 'dealer_notifications', ['tractor_vin'], unique=False)
    op.drop_index(op.f('idx_tractors_id'), table_name='tractors')
    op.drop_index(op.f('idx_tractors_last_activity'), table_name='tractors')
    op.drop_index(op.f('idx_tractors_vin'), table_name='tractors')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_tractors_vin'), 'tractors', ['vin'], unique=False)
    op.create_index(op.f('idx_tractors_last_activity'), 'tractors', ['last_activity'], unique=False)
    op.create_index(op.f('idx_tractors_id'), 'tractors', ['id'], unique=False)
    op.drop_index(op.f('ix_dealer_notifications_tractor_vin'), table_name='dealer_notifications')
    op.drop_index(op.f('ix_dealer_notifications_tractor_id'), table_name='dealer_notifications')
    op.drop_index(op.f('ix_dealer_notifications_is_read'), table_name='dealer_notifications')
    op.drop_index(op.f('ix_dealer_notifications_id'), table_name='dealer_notifications')
    op.drop_index(op.f('ix_dealer_notifications_dealer_id'), table_name='dealer_notifications')
    op.drop_table('dealer_notifications')
    # ### end Alembic commands ###
