"""Checking differences

Revision ID: e8fd0ae2ee85
Revises: c93d55a5b266
Create Date: 2026-03-31 09:59:54.993160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8fd0ae2ee85'
down_revision: Union[str, Sequence[str], None] = 'c93d55a5b266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('support_message', 'is_closed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_tractors_id'), table_name='tractors')
    op.drop_index(op.f('idx_tractors_last_activity'), table_name='tractors')
    op.drop_index(op.f('idx_tractors_vin'), table_name='tractors')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_tractors_vin'), 'tractors', ['vin'], unique=False)
    op.create_index(op.f('idx_tractors_last_activity'), 'tractors', ['last_activity'], unique=False)
    op.create_index(op.f('idx_tractors_id'), 'tractors', ['id'], unique=False)
    op.alter_column('support_message', 'is_closed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
